version: "3"
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5000 hello:app --reload # --timeout 5
    # command: flask run --host 0.0.0.0
    environment:
        - FLASK_APP=hello.py
        - FLASK_DEBUG=1
        - PYTHONUNBUFFERED=1
    ports:
        - "5000:5000"
    volumes:
        - ./:/root